{
  "hash": "7a55a5e7379133e4656b53ae0c6c6cd8",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Example Analysis\"\nformat: html\nbibliography: references.bib\ncss: styles.css\n---\n\n\n# Introduction\n\nI am using the `ToothGrowth` dataset for t\nhis example analysis.\n\n![\"George the amazing guinea pig\" by Plath81, licensed under CC BY-SA 3.0](images/gpig.jpg){width=\"600px\"}\n\n<details>\n\n<summary>Criteria Met</summary>\n\nYour analysis must include one image or table (not one you created yourself, but one you have saved locally or one from the web).\n\n</details>\n\n# Guiding Question\n\nHow does the dose and type of supplement — either Vitamin C (VC) or Orange Juice (OJ) — affect the length of odontoblasts (type of specialized cells that contribute to tooth development) in guinea pigs, and are there noticeable differences between the two in terms of how much they help teeth grow?\n\n<details>\n\n<summary>Criteria Met</summary>\n\nWhat is the question you aim to answer with the data and data analysis?\n\n</details>\n\n# Intended Audience\n\nBiostatisticians, public health researchers, and data science students.\n\n<details>\n\n<summary>Criteria Met</summary>\n\nWho is the intended audience?\n\n</details>\n\n# Data Source\n\nThe ToothGrowth dataset originates from an experiment on guinea pig tooth development conducted by C. I. Bliss, published in The Statistics of Bioassay [@bliss1952]. It is a built-in dataset in R [@toothgrowth2021]. Relevant studies on vitamin C's impact on odontoblast growth are available on PubMed [@pubmed20294344]; [@pubmed22420233].\n\n[Link to the dataset](https://www.rdocumentation.org/packages/datasets/versions/3.6.2/topics/ToothGrowth)\n\n<details>\n\n<summary>Criteria Met</summary>\n\nYou must describe and link to where the original data come from that you chose.\n\n</details>\n\n# Data Dictionary\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(knitr)\n\ndata_dictionary <- data.frame(\n  Variable = c(\"len\", \"supp\", \"dose\"),\n  Description = c(\"Length of tooth growth measured\", \n                  \"Type of supplement given\", \n                  \"Dose level of the supplement\"),\n  `Type` = c(\"Numeric\", \"Categorical\", \"Numeric\"),\n  `Range` = c(\"Continuous values in mm (e.g., 4.2, 33.9)\",\n              \"VC (Vitamin C), OJ (Orange Juice)\",\n              \"0.5, 1.0, 2.0 (in milligrams)\")\n)\nkable(data_dictionary, caption = \"Data Dictionary for ToothGrowth Dataset\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Data Dictionary for ToothGrowth Dataset\n\n|Variable |Description                     |Type        |Range                                     |\n|:--------|:-------------------------------|:-----------|:-----------------------------------------|\n|len      |Length of tooth growth measured |Numeric     |Continuous values in mm (e.g., 4.2, 33.9) |\n|supp     |Type of supplement given        |Categorical |VC (Vitamin C), OJ (Orange Juice)         |\n|dose     |Dose level of the supplement    |Numeric     |0.5, 1.0, 2.0 (in milligrams)             |\n\n\n:::\n:::\n\n\n<details>\n\n<summary>Criteria Met</summary>\n\nYou must include a link to a data dictionary for the data or create one inside the webpage.\n\n</details>\n\n# Data Analysis\n\n<details>\n\n<summary>Setting up the R environment</summary>\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Setting up R environment\n\nif(!require(dplyr)) install.packages(\"dplyr\")\nif(!require(tidyr)) install.packages(\"tidyr\")\nif(!require(ggplot2)) install.packages(\"ggplot2\")\nif(!require(knitr)) install.packages(\"knitr\")\nif(!require(DT)) install.packages(\"DT\")\nif(!require(DT)) install.packages(\"tidyverse\")\n\n\nlibrary(dplyr)\nlibrary(tidyr)\nlibrary(ggplot2)\nlibrary(knitr)\nlibrary(DT)\nlibrary(tidyverse)\n```\n:::\n\n\n</details>\n\nFirst, I filter the ToothGrowth dataset to include only observations where the dose is greater than 0.5 mg. This ensures that the focus is on doses that may have a stronger biological effect on tooth growth!\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(\"ToothGrowth\")\n\ntooth_filtered <- ToothGrowth %>%\n  filter(dose > 0.5)\n```\n:::\n\n\nI then create a new categorical variable, `len_category`, which classifies tooth lengths into \"Short\" (\\<15 mm) and \"Long\" (≥15 mm). This helps in understanding the distribution of shorter and longer tooth lengths across different doses and supplement types.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntooth_categorized <- tooth_filtered %>% \n  mutate(len_category = ifelse(len < 15, \"Short\", \"Long\"))\n```\n:::\n\n\nI calculate the average tooth length for each combination of supplement type and dose using the `group_by` and `summarize` functions. This will be important for comparing average growth across different groups.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntooth_summary <- ToothGrowth %>% \n  group_by(supp, dose) %>% \n  summarize(avg_length = mean(len), .groups = \"drop\")\n```\n:::\n\n\nI also sort the data by average length in descending order.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntooth_sorted <- tooth_summary %>% \n  arrange(desc(avg_length))\n```\n:::\n\n\nFinally, I transform the summarized data into a wide format using `pivot_wider` to facilitate easy visualization in subsequent steps.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntooth_wide <- tooth_summary %>%\n  pivot_wider(names_from = dose, values_from = avg_length)\n```\n:::\n\n\n<details>\n\n<summary>Criteria Met</summary>\n\nYour analysis must include some minimal form of data wrangling with you using at least five different functions from `dplyr` or `tidyr`.\n\n</details>\n\n# Data Visualizations\n\n**Your analysis must include the use of at least 1 margin content.**\n\nAfter wrangling the data, I use the newly-created variables along with the `ggplot` package to create different types of plots. First is a stacked bar plot displaying the proportion of \"Short\" vs. \"Long\" tooth lengths by dose, separated by supplement type. This plot uses `geom_bar()` and `facet_wrap()`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(tooth_categorized, aes(x = dose, fill = len_category)) +\n  geom_bar(position = \"fill\") +\n  facet_wrap(~ supp) +\n  labs(\n    title = \"Proportion of 'Short' vs. 'Long' Tooth Lengths by Dose\",\n    subtitle = \"Faceted by Supplement Type to Compare Distribution\",\n    x = \"Dose (mg)\",\n    y = \"Proportion\",\n    fill = \"Length Category\",\n    caption = \"Data Source: ToothGrowth Dataset\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](example-analysis_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n<details>\n\n<summary>Criteria Met</summary>\n\nAt least one plot should use a type of faceting (facet_grid() or facet_wrap()).\n\nPlots should have titles, subtitles, captions, and human-understandable axis labels.\n\nYour analysis should include at least three plots with you using at least three different geom\\_() functions from ggplot2 (or another package with geom\\_\\*() functions). First plot.\n\n</details>\n\n::: callout-note\nThis plot shows how the proportion of \"Long\" tooth lengths increases with dose and compares the distribution between Vitamin C and Orange Juice.\n:::\n\n<details>\n\n<summary>Criteria Met</summary>\n\nYour analysis must include at least two different callout blocks. First callout block.\n\n</details>\n\nI then use `geom_jitter()` to add random noise to the position of the points, which helps visualize the distribution of individual tooth lengths for each dose and supplement type.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(tooth_filtered, aes(x = dose, y = len, color = supp)) +\n  geom_jitter(width = 0.1, height = 0) +  # Adding jitter to avoid overlap\n  labs(\n    title = \"Jittered Scatter Plot of Tooth Length by Dose and Supplement Type\",\n    subtitle = \"Individual data points show variability in tooth length\",\n    x = \"Dose (mg)\",\n    y = \"Tooth Length (mm)\",\n    color = \"Supplement Type\",\n    caption = \"Jitter applied to better visualize overlapping points\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](example-analysis_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n<details>\n\n<summary>Criteria Met</summary>\n\nPlots should have titles, subtitles, captions, and human-understandable axis labels.\n\nYour analysis should include at least three plots with you using at least three different geom\\_() functions from ggplot2 (or another package with geom\\_\\*() functions). Second plot.\n\n</details>\n\n::: {.callout-tip title=\"Heatmap Tip!\"}\nThis scatter plot with jitter is especially useful for observing the spread and clustering of data points and detecting patterns and outliers!\n:::\n\n<details>\n\n<summary>Criteria Met</summary>\n\nYour analysis must include at least two different callout blocks. Second callout block.\n\n</details>\n\nI create a line plot using `geom_line()` and `geom_point()` to illustrate the trend of average tooth length with increasing doses for each supplement type.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(tooth_summary, aes(x = as.numeric(dose), y = avg_length, color = supp, group = supp)) +\n  geom_line() +\n  geom_point() +\n  labs(\n    title = \"Average Tooth Length Across Doses by Supplement Type\",\n    subtitle = \"Dose-Response Relationship for Tooth Growth\",\n    x = \"Dose (mg)\",\n    y = \"Average Tooth Length (mm)\",\n    color = \"Supplement Type\",\n    caption = \"Data Source: ToothGrowth Dataset\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](example-analysis_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\n<details>\n\n<summary>Criteria Met</summary>\n\nPlots should have titles, subtitles, captions, and human-understandable axis labels.\n\nYour analysis should include at least three plots with you using at least three different geom\\_() functions from ggplot2 (or another package with geom\\_\\*() functions). Third plot.\n\n</details>\n\nFinally, to confirm patterns observed thus far, I use `geom_density()` to plot the density curves of tooth length distributions for VC and OJ.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(tooth_filtered, aes(x = len, fill = supp)) +\n  geom_density(alpha = 0.4) +  # Use alpha to make the plot semi-transparent\n  labs(\n    title = \"Density Plot of Tooth Length by Supplement Type\",\n    subtitle = \"Comparing the distribution of tooth lengths between Vitamin C and Orange Juice\",\n    x = \"Tooth Length (mm)\",\n    y = \"Density\",\n    fill = \"Supplement Type\",\n    caption = \"Density curves show where tooth lengths are most concentrated\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](example-analysis_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\n<details>\n\n<summary>Criteria Met</summary>\n\nPlots should have titles, subtitles, captions, and human-understandable axis labels.\n\nYour analysis should include at least three plots with you using at least three different geom\\_() functions from ggplot2 (or another package with geom\\_\\*() functions). Fourth plot.\n\n</details>\n\n::: callout-warning\nOverlapping density curves can obscure the underlying variabiity of individual data points. Consider examining this plot in the context of other plots above for a more comprehensive picture of the distribution.\n:::\n\n<details>\n\n<summary>Criteria Met</summary>\n\nYour analysis must include at least two different callout blocks. Third callout block.\n\n</details>\n\n# Statistical Analysis Using ANOVA and Tukey's Test\n\nTo test the effects of dose and supplement type on tooth length, I employ a two-way ANOVA followed by Tukey's post-hoc test.\n\nThe two-way ANOVA tests three main hypotheses:\n\n-   Whether the type of supplement (Vitamin C or Orange Juice) has a significant effect on tooth length.\n\n-   Whether the dose level (0.5 mg, 1.0 mg, 2.0 mg) has a significant effect on tooth length.\n\n-   Whether there is an interaction effect between the supplement type and dose level.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova_model <- aov(len ~ supp * dose, data = ToothGrowth)\nanova_results <- summary(anova_model)\nprint(anova_results)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Df Sum Sq Mean Sq F value   Pr(>F)    \nsupp         1  205.4   205.4  12.317 0.000894 ***\ndose         1 2224.3  2224.3 133.415  < 2e-16 ***\nsupp:dose    1   88.9    88.9   5.333 0.024631 *  \nResiduals   56  933.6    16.7                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nThe Tukey's test then is used to perform pairwise comparisons between group means to identify which specific groups differ significantly from each other. This controls for Type I error across comparisons!\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntukey_results <- TukeyHSD(anova_model)\nprint(tukey_results)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Tukey multiple comparisons of means\n    95% family-wise confidence level\n\nFit: aov(formula = len ~ supp * dose, data = ToothGrowth)\n\n$supp\n      diff       lwr       upr     p adj\nVC-OJ -3.7 -5.811942 -1.588058 0.0008936\n```\n\n\n:::\n:::\n\n\n# Summary\n\nFrom the visualizations and the statistical analysis, it can be observed that:\n\n1.  The line plot illustrates a strong dose-response relationship, showing that higher doses of both Orange Juice (OJ) and Vitamin C (VC) result in longer tooth growth. At every dose level, OJ exceeds VC in promoting tooth length. The jittered scatter plot adds to this relationship by displaying individual tooth lengths, highlighting the spread of data points while emphasizing the upward trend in growth as the dose increases.\n\n2.  The stacked bar plot shows how the proportion of \"Long\" lengths (≥15 mm) becomes more prominent at higher doses. This effect is pronounced for OJ. THe relationship between dose, supplement type, and tooth length is made clear when all these plots are considered together.\n\n3.  The two-way ANOVA results show that both dose ($p < 2 \\times 10^{-16}$) and supplement type ($p = 0.000894$) significantly influence tooth length, and the significant interaction effect ($p = 0.0246$) shows that the impact of dosing DOES vary depending on the supplement. Tukey's post-hoc reveals that OJ leads to an average increase of 3.7mm in tooth length compared to VC ($p = 0.0009$).\n\n4.  All in all, the findings indicate that OJ, especially at higher doses, is the superior supplement for tooth growth in guinea pigs compared to VC.\n\n<details>\n\n<summary>Criteria Met</summary>\n\nYou must summarize your analysis and/or results with a paragraph (4-6 sentences).\n\n</details>\n\n# Functions Used\n\n`dplyr` package: `mutate()`, `group_by()`, `summarize()`, `arrange()`, `filter()`\n\n`tidyr` package: `pivot_wider()`\n\n`ggplot2` package: `ggplot()`, `geom_bar()`, `facet_wrap()`, `geom_jitter()`, `geom_line()`, `geom_point()`, `geom_density()`\n\n<details>\n\n<summary>Criteria Met</summary>\n\nAt the end of the data analysis, list out each of the functions you used from each of the packages (dplyr, tidyr, and ggplot2) to help the TA with respect to making sure you met all the requirements described above.\n\n</details>\n\n<details>\n\n<summary>Criteria Met</summary>\n\nYour analysis must include a .bib file, which you use to reference at least three unique citations. For example, it could be to a website or paper from where the original data came from or it could be to a paper describing a method you are using to analyze the data.\n\n</details>\n",
    "supporting": [
      "example-analysis_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}